# Docker compose setup for running tests against the dev version of the app
# Use with:
#   UID=$(id -u) GID=$(id -g) docker compose -f docker-compose.yml -f docker-compose-test.yml up --build

services:
  # docker compose run --build test-not-data
  # MAKE SURE TO RESET YOUR DATA WITH
  # $ git checkout data/wikibase-test-data.db
  test-not-data:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    entrypoint:
      - pytest
    command:
      - -m
      - "not data"
      - --cov=.
      - --cov-report
      - html:cov_html
      - --order-dependencies
    environment:
      SETTINGS_FILE: test-settings.ini
    user: "${UID}:${GID}"

  # docker compose run --build test-data
  test-data:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    entrypoint:
      - pytest
    command:
      - -m
      - data
    environment:
      SETTINGS_FILE: test-settings.ini
    user: "${UID}:${GID}"
