# Docker compose setup for developing the app
# Use with:
#   docker compose up --build

services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - 8000:8000

  # docker compose run --build test-not-data
  # MAKE SURE TO RESET YOUR DATA WITH
  # $ git checkout data/wikibase-test-data.db
  test-not-data:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    entrypoint:
      - pytest
    command:
      - -m
      - "not data"
      - --cov=.
      - --cov-report
      - html:cov_html
      - --order-dependencies
    environment:
      SETTINGS_FILE: test-settings.ini

  # docker compose run --build test-data
  test-data:
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    entrypoint:
      - pytest
    command:
      - -m
      - data
    environment:
      SETTINGS_FILE: test-settings.ini
