events {}

http {
  server {
    listen 80;
    server_name wikibase-metadata.wmcloud.org explorer.wikiba.se;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name wikibase-metadata.wmcloud.org;

    location /graphql {
      proxy_set_header Host $host;
      proxy_pass http://backend:8000;
    }

    location /csv {
      proxy_set_header Host $host;
      proxy_pass http://backend:8000;
    }

    location / {
      proxy_set_header Host $host;
      proxy_pass http://frontend:3000;
    }
  }

  server {
    listen 443 ssl;
    server_name explorer.wikiba.se;

    ssl_certificate /etc/letsencrypt/live/explorer.wikiba.se/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/explorer.wikiba.se/privkey.pem;

    location /graphql {
      proxy_set_header Host $host;
      proxy_pass http://backend:8000;
    }

    location /csv {
      proxy_set_header Host $host;
      proxy_pass http://backend:8000;
    }

    location / {
      proxy_set_header Host $host;
      proxy_pass http://frontend:3000;
    }
  }
}