"""recent changes

Revision ID: 07663ad9d60d
Revises: bcc81afe3bc3
Create Date: 2025-07-28 14:47:55.185419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07663ad9d60d"
down_revision: Union[str, None] = "bcc81afe3bc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_recent_changes_observation",
        sa.Column("human_change_count", sa.Integer(), nullable=False),
        sa.Column("human_change_user_count", sa.Integer(), nullable=False),
        sa.Column("bot_change_count", sa.Integer(), nullable=False),
        sa.Column("bot_change_user_count", sa.Integer(), nullable=False),
        sa.Column("first_change_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_change_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_recent_changes_observation")
    # ### end Alembic commands ###
