"""Software Model

Revision ID: 0833cb54870f
Revises: e3ecd40e3851
Create Date: 2024-10-16 23:03:09.901779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0833cb54870f"
down_revision: Union[str, None] = "e3ecd40e3851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_software",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "software_type",
            sa.Enum(
                "SOFTWARE", "SKIN", "EXTENSION", "LIBRARY", name="wikibasesoftwaretype"
            ),
            nullable=False,
        ),
        sa.Column("software_name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("latest_version", sa.String(), nullable=True),
        sa.Column("quarterly_download_count", sa.Integer(), nullable=True),
        sa.Column("public_wiki_count", sa.Integer(), nullable=True),
        sa.Column("mw_bundled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "software_type", "software_name", name="unique_software_type_name"
        ),
    )

    op.create_table(
        "wikibase_software_tag",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "wikibase_software_tag_xref",
        sa.Column("wikibase_software_id", sa.Integer(), nullable=False),
        sa.Column("wikibase_software_tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_software_id"],
            ["wikibase_software.id"],
            name="foreign_wikibase_software_id",
        ),
        sa.ForeignKeyConstraint(
            ["wikibase_software_tag_id"],
            ["wikibase_software_tag.id"],
            name="foreign_wikibase_software_tag_id",
        ),
        sa.PrimaryKeyConstraint("wikibase_software_id", "wikibase_software_tag_id"),
    )

    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.add_column(
            sa.Column("wikibase_software_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "software", "wikibase_software", ["wikibase_software_id"], ["id"]
        )
    with op.get_bind() as conn:
        conn.execute(sa.text("""INSERT INTO wikibase_software (software_type, software_name)
SELECT DISTINCT software_type, software_name
FROM wikibase_software_version
ORDER BY software_type, software_name"""))
        conn.execute(sa.text("""UPDATE wikibase_software_version
SET wikibase_software_id = wikibase_software.id
FROM wikibase_software
WHERE wikibase_software_version.software_name = wikibase_software.software_name AND wikibase_software_version.software_type = wikibase_software.software_type"""))
        conn.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.drop_constraint("software", type_="foreignkey")
        batch_op.drop_column("wikibase_software_id")
    op.drop_table("wikibase_software_tag_xref")
    op.drop_table("wikibase_software_tag")
    op.drop_table("wikibase_software")
    # ### end Alembic commands ###
