"""urls

Revision ID: 0b1e399e0e78
Revises: 8c2df588e047
Create Date: 2024-06-26 15:19:17.270449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b1e399e0e78"
down_revision: Union[str, None] = "8c2df588e047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_url",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column(
            "url_type",
            sa.Enum(
                "base_url",
                "action_query_url",
                "index_query_url",
                "sparql_endpoint_url",
                "sparql_query_url",
                "special_version",
                "special_base",
                name="wikibaseurltypes",
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_url")
    # ### end Alembic commands ###
