"""Only Month

Revision ID: 0de663bb9c13
Revises: e0cad634525c
Create Date: 2024-11-18 13:50:09.959941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0de663bb9c13"
down_revision: Union[str, None] = "e0cad634525c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_log_observation")
    with op.batch_alter_table("wikibase_log_observation_month") as batch_op:
        batch_op.alter_column("first", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("wikibase_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("anything", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("date", existing_type=sa.DATETIME(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month") as batch_op:
        batch_op.alter_column("date", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("anything", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("wikibase_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("first", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_table(
        "wikibase_log_observation",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("wikibase_id", sa.INTEGER(), nullable=False),
        sa.Column("anything", sa.BOOLEAN(), nullable=False),
        sa.Column("date", sa.DATETIME(), nullable=False),
        sa.Column("first_log_date", sa.DATETIME(), nullable=True),
        sa.Column("last_log_date", sa.DATETIME(), nullable=True),
        sa.Column("last_log_user_type", sa.VARCHAR(length=7), nullable=True),
        sa.Column("first_month_id", sa.INTEGER(), nullable=True),
        sa.Column("last_month_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["first_month_id"],
            ["wikibase_log_observation_month.id"],
            name="first_month",
        ),
        sa.ForeignKeyConstraint(
            ["last_month_id"], ["wikibase_log_observation_month.id"], name="last_month"
        ),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
