"""rename ttfv

Revision ID: 0ec4bac56660
Revises: 15a3bcb31042
Create Date: 2025-06-06 13:38:16.874962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec4bac56660'
down_revision: Union[str, None] = '15a3bcb31042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('wikibase_initial_value_observation', 'wikibase_time_to_first_value_observation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table( 'wikibase_time_to_first_value_observation','wikibase_initial_value_observation')
    # ### end Alembic commands ###
