"""Enum Fixes

Revision ID: 12184e80034d
Revises: be21c6bee8af
Create Date: 2024-08-20 16:05:58.024054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12184e80034d"
down_revision: Union[str, None] = "be21c6bee8af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


old_log_type_values = [
    "ABUSE_FILTER_CREATE",
    "ABUSE_FILTER_MODIFIY",
    "ACHIEVEMENT_BADGE",
    "APPROVE",
    "COMMENTS_CREATE",
    "COMMENTS_DELETE",
    "CONSUMER_APPROVE",
    "CONSUMER_CREATE",
    "CONSUMER_DISABLE",
    "CONSUMER_PROPOSE",
    "CONSUMER_REJECT",
    "CONSUMER_UPDATE",
    "CONFIG_UPDATE",
    "CONTENT_MODEL_CREATE",
    "CONTENT_MODEL_CHANGE",
    "DATADUMP_DELETE",
    "DATADUMP_GENERATE",
    "EVENT_DELETE",
    "EXPORT_PDF",
    "FEEDBACK_CREATE",
    "FEEDBACK_FEATURE",
    "FEEDBACK_FLAG",
    "FEEDBACK_FLAG_INAPPROPRIATE",
    "FEEDBACK_HIDE",
    "FEEDBACK_NO_ACTION",
    "FEEDBACK_RESOLVE",
    "IMPORT",
    "IMPORT_HTML",
    "INTERWIKI_CREATE",
    "INTERWIKI_DELETE",
    "INTERWIKI_EDIT",
    "ITEM_CREATE",
    "ITEM_DELETE",
    "LOCK_FLOW_LOCK_TOPIC",
    "MEDIA_APPROVE",
    "MEDIA_OVERWRITE",
    "MEDIA_REVERT",
    "MEDIA_UPLOAD",
    "MOVE",
    "PAGE_CREATE",
    "PAGE_DELETE",
    "PAGE_TRANSLATE",
    "PAGE_TRANSLATE_DELETE_FOK",
    "PAGE_TRANSLATE_DELETE_LOK",
    "PAGE_TRANSLATE_MARK",
    "PAGE_TRANSLATE_UNMARK",
    "PAGE_UPDATE_LANGUAGE",
    "PATROL",
    "PATROL_AUTO",
    "PROFILE",
    "PROPERTY_CREATE",
    "PROPERTY_DELETE",
    "PROTECT",
    "REDIRECT_DELETE",
    "REDIRECT_MOVE",
    "REVISION_DELETE",
    "TABLE_CREATE",
    "TABLE_DELETE",
    "TAG_CREATE",
    "THANK",
    "UNAPPROVE",
    "UNDO_DELETE",
    "UNPROTECT",
    "USER_BLOCK",
    "USER_UNBLOCK",
    "USER_CREATE",
    "USER_DELETE",
    "USER_MERGE",
    "USER_RENAME",
    "USER_RIGHTS",
    "WIKI_FARM",
    "WIKI_GROUP_DELETE",
    "WIKI_NAMESPACES",
    "WIKI_RIGHTS",
    "WIKI_SETTINGS",
]
new_log_type_values = [
    "ABUSE_FILTER_CREATE",
    "ABUSE_FILTER_MODIFIY",
    "ACHIEVEMENT_BADGE",
    "APPROVE",
    "COMMENTS_CREATE",
    "COMMENTS_DELETE",
    "CONSUMER_APPROVE",
    "CONSUMER_CREATE",
    "CONSUMER_DISABLE",
    "CONSUMER_PROPOSE",
    "CONSUMER_REJECT",
    "CONSUMER_UPDATE",
    "CONFIG_UPDATE",
    "CONTENT_MODEL_CREATE",
    "CONTENT_MODEL_CHANGE",
    "DATADUMP_DELETE",
    "DATADUMP_GENERATE",
    "EVENT_DELETE",
    "EXPORT_PDF",
    "FEEDBACK_CREATE",
    "FEEDBACK_FEATURE",
    "FEEDBACK_FLAG",
    "FEEDBACK_FLAG_INAPPROPRIATE",
    "FEEDBACK_HIDE",
    "FEEDBACK_NO_ACTION",
    "FEEDBACK_RESOLVE",
    "IMPORT",
    "IMPORT_HTML",
    "INTERWIKI_CREATE",
    "INTERWIKI_DELETE",
    "INTERWIKI_EDIT",
    "ITEM_CREATE",
    "ITEM_DELETE",
    "LOCK_FLOW_LOCK_TOPIC",
    "MEDIA_APPROVE",
    "MEDIA_OVERWRITE",
    "MEDIA_REVERT",
    "MEDIA_UPLOAD",
    "MOVE",
    "PAGE_CREATE",
    "PAGE_DELETE",
    "PAGE_TRANSLATE",
    "PAGE_TRANSLATE_DELETE_FOK",
    "PAGE_TRANSLATE_DELETE_LOK",
    "PAGE_TRANSLATE_MARK",
    "PAGE_TRANSLATE_UNMARK",
    "PAGE_UPDATE_LANGUAGE",
    "PATROL",
    "PATROL_AUTO",
    "PROFILE",
    "PROPERTY_CREATE",
    "PROPERTY_DELETE",
    "PROTECT",
    "REDIRECT_DELETE",
    "REDIRECT_MOVE",
    "REVISION_DELETE",
    "TABLE_CREATE",
    "TABLE_DELETE",
    "TAG_CREATE",
    "THANK",
    "UNAPPROVE",
    "UNDO_DELETE",
    "UNPROTECT",
    "USER_BLOCK",
    "USER_UNBLOCK",
    "USER_CREATE",
    "USER_DELETE",
    "USER_MERGE",
    "USER_RENAME",
    "USER_RIGHTS",
    "WIKI_FARM",
    "WIKI_GROUP_DELETE",
    "WIKI_NAMESPACES",
    "WIKI_RIGHTS",
    "WIKI_SETTINGS",
]


old_url_type_values = [
    "BASE_URL",
    "ACTION_QUERY_URL",
    "INDEX_QUERY_URL",
    "SPARQL_ENDPOINT_URL",
    "SPARQL_QUERY_URL",
    "SPECIAL_VERSION_URL",
]
new_url_type_values = [
    "BASE_URL",
    "ACTION_QUERY_URL",
    "INDEX_QUERY_URL",
    "SPARQL_ENDPOINT_URL",
    "SPARQL_QUERY_URL",
    "SPECIAL_STATISTICS_URL",
    "SPECIAL_VERSION_URL",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.alter_column(
            "log_type",
            existing_type=sa.Enum(
                *old_log_type_values, name="wikibaselogtype"
            ).with_variant(
                sa.VARCHAR(length=max([len(x) for x in old_log_type_values])), "sqlite"
            ),
            type_=sa.Enum(*new_log_type_values, name="wikibaselogtype").with_variant(
                sa.VARCHAR(length=max([len(x) for x in new_log_type_values])), "sqlite"
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("wikibase_url") as batch_op:
        batch_op.alter_column(
            "url_type",
            existing_type=sa.Enum(
                *old_url_type_values, name="wikibaseurltype"
            ).with_variant(
                sa.VARCHAR(length=max([len(x) for x in old_url_type_values])), "sqlite"
            ),
            type_=sa.Enum(*new_url_type_values, name="wikibaseurltype").with_variant(
                sa.VARCHAR(length=max([len(x) for x in new_url_type_values])), "sqlite"
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_url") as batch_op:
        batch_op.alter_column(
            "url_type",
            existing_type=sa.Enum(
                *new_url_type_values, name="wikibaseurltype"
            ).with_variant(
                sa.VARCHAR(length=max([len(x) for x in new_url_type_values])), "sqlite"
            ),
            type_=sa.Enum(*old_url_type_values, name="wikibaseurltype").with_variant(
                sa.VARCHAR(length=max([len(x) for x in old_url_type_values])), "sqlite"
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.alter_column(
            "log_type",
            existing_type=sa.Enum(
                *new_log_type_values, name="wikibaselogtype"
            ).with_variant(
                sa.VARCHAR(length=max([len(x) for x in new_log_type_values])), "sqlite"
            ),
            type_=sa.Enum(*old_log_type_values, name="wikibaselogtype").with_variant(
                sa.VARCHAR(length=max([len(x) for x in old_log_type_values])), "sqlite"
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
