"""initial-value

Revision ID: 15a3bcb31042
Revises: 215716d3ef0e
Create Date: 2025-05-28 13:16:31.306053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15a3bcb31042"
down_revision: Union[str, None] = "215716d3ef0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_initial_value_observation",
        sa.Column("initial_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wikibase_item_date",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "wikibase_initial_value_observation_id", sa.Integer(), nullable=False
        ),
        sa.Column("q", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_initial_value_observation_id"],
            ["wikibase_initial_value_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_initial_value_observation_id", "q", name="unique_observation_q"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_item_date")
    op.drop_table("wikibase_initial_value_observation")
    # ### end Alembic commands ###
