"""Wikibase URLs

Revision ID: 42b4ede5bdd8
Revises: e2f94a8e2beb
Create Date: 2024-06-17 10:36:51.579720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42b4ede5bdd8"
down_revision: Union[str, None] = "e2f94a8e2beb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("action_query_url", sa.String(), nullable=True),
        sa.Column("index_query_url", sa.String(), nullable=True),
        sa.Column("sparql_query_url", sa.String(), nullable=True),
        sa.Column("sparql_endpoint_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase")
    # ### end Alembic commands ###
