"""Unique Constraints

Revision ID: 43064b39c3a0
Revises: c585ae1a8a67
Create Date: 2024-07-16 23:35:17.697990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43064b39c3a0"
down_revision: Union[str, None] = "c585ae1a8a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.alter_column(
            "log_type",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.Enum(
                "ABUSE_FILTER_CREATE",
                "COMMENTS_CREATE",
                "COMMENTS_DELETE",
                "CONSUMER_APPROVE",
                "CONSUMER_CREATE",
                "CONSUMER_PROPOSE",
                "CONSUMER_REJECT",
                "IMAGE_OVERWRITE",
                "IMAGE_REVERT",
                "IMAGE_UPLOAD",
                "IMPORT",
                "INTERWIKI_CREATE",
                "INTERWIKI_DELETE",
                "INTERWIKI_EDIT",
                "ITEM_CREATE",
                "ITEM_DELETE",
                "MOVE",
                "PAGE_CREATE",
                "PAGE_DELETE",
                "PATROL",
                "PATROL_AUTO",
                "PROPERTY_CREATE",
                "PROPERTY_DELETE",
                "PROTECT",
                "TAG_CREATE",
                "UNDO_DELETE",
                "USER_BLOCK",
                "USER_UNBLOCK",
                "USER_CREATE",
                "USER_DELETE",
                "USER_MERGE",
                "USER_RENAME",
                "USER_RIGHTS",
                "WIKI_NAMESPACES",
                "WIKI_RIGHTS",
                "WIKI_SETTINGS",
                name="wikibaselogtype",
            ).with_variant(sa.String, "sqlite"),
            existing_nullable=False,
        )
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.create_unique_constraint(
            "unique_observation_user_type",
            ["log_month_observation_id", "user_type"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.drop_constraint(
            "unique_observation_user_type",
            type_="unique",
        )
    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.alter_column(
            "log_type",
            existing_type=sa.Enum(
                "ABUSE_FILTER_CREATE",
                "COMMENTS_CREATE",
                "COMMENTS_DELETE",
                "CONSUMER_APPROVE",
                "CONSUMER_CREATE",
                "CONSUMER_PROPOSE",
                "CONSUMER_REJECT",
                "IMAGE_OVERWRITE",
                "IMAGE_REVERT",
                "IMAGE_UPLOAD",
                "IMPORT",
                "INTERWIKI_CREATE",
                "INTERWIKI_DELETE",
                "INTERWIKI_EDIT",
                "ITEM_CREATE",
                "ITEM_DELETE",
                "MOVE",
                "PAGE_CREATE",
                "PAGE_DELETE",
                "PATROL",
                "PATROL_AUTO",
                "PROPERTY_CREATE",
                "PROPERTY_DELETE",
                "PROTECT",
                "TAG_CREATE",
                "UNDO_DELETE",
                "USER_BLOCK",
                "USER_UNBLOCK",
                "USER_CREATE",
                "USER_DELETE",
                "USER_MERGE",
                "USER_RENAME",
                "USER_RIGHTS",
                "WIKI_NAMESPACES",
                "WIKI_RIGHTS",
                "WIKI_SETTINGS",
                name="wikibaselogtype",
            ).with_variant(sa.String, "sqlite"),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
