"""Non-Functional

Revision ID: 4c5fcad6037c
Revises: e6685295bb5c
Create Date: 2025-03-18 21:55:44.020746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import update
from sqlalchemy.orm import Session

from model.database.wikibase_url_model import WikibaseURLModel


# revision identifiers, used by Alembic.
revision: str = "4c5fcad6037c"
down_revision: Union[str, None] = "e6685295bb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_url") as batch_op:
        batch_op.add_column(sa.Column("non_func", sa.Boolean(), nullable=True))

    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(update(WikibaseURLModel).values(non_functional=False))
    session.commit()

    with op.batch_alter_table("wikibase_url") as batch_op:
        batch_op.alter_column("non_func", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_url") as batch_op:
        batch_op.drop_column("non_func")
    # ### end Alembic commands ###
