"""Software Version

Revision ID: 4e46b70c3f46
Revises: d411cfb9428e
Create Date: 2024-06-25 11:27:06.420396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e46b70c3f46"
down_revision: Union[str, None] = "d411cfb9428e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_software_version_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wikibase_software_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "wikibase_software_version_observation_id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "software_type",
            sa.Enum(
                "software", "skin", "extension", "library", name="wikibasesoftwaretypes"
            ),
            nullable=False,
        ),
        sa.Column("software_name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("version_hash", sa.String(), nullable=True),
        sa.Column("version_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wikibase_software_version_observation_id"],
            ["wikibase_software_version_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_software_version_observation_id",
            "software_type",
            "software_name",
            name="unique_observation_software_type_name",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_software_version")
    op.drop_table("wikibase_software_version_observation")
    # ### end Alembic commands ###
