"""Mark Test

Revision ID: 50eab022143d
Revises: fd116456e347
Create Date: 2024-07-24 16:39:00.196271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eab022143d'
down_revision: Union[str, None] = 'fd116456e347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikibase', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wikibase', 'test')
    # ### end Alembic commands ###
