"""statistics

Revision ID: 67cb5d75f92b
Revises: 12184e80034d
Create Date: 2024-08-20 16:23:59.751853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67cb5d75f92b"
down_revision: Union[str, None] = "12184e80034d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_statistics_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("content_pages", sa.Integer(), nullable=True),
        sa.Column("total_edits", sa.Integer(), nullable=True),
        sa.Column("content_words", sa.Integer(), nullable=True),
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.Column("active_users", sa.Integer(), nullable=True),
        sa.Column("total_admin", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_statistics_observation")
    # ### end Alembic commands ###
