"""Wikibase User Observation

Revision ID: 7b6bec51442f
Revises: 42b4ede5bdd8
Create Date: 2024-06-17 10:58:13.729786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b6bec51442f"
down_revision: Union[str, None] = "42b4ede5bdd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_user_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wikibase_user_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wikibase_user_observation_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_user_observation_id", sa.Integer(), nullable=False),
        sa.Column("wikibase_user_group_id", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("implicit", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_user_group_id"], ["wikibase_user_group.id"], name="group"
        ),
        sa.ForeignKeyConstraint(
            ["wikibase_user_observation_id"],
            ["wikibase_user_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_user_observation_group")
    op.drop_table("wikibase_user_observation")
    op.drop_table("wikibase_user_group")
    # ### end Alembic commands ###
