"""region

Revision ID: 82fb182288aa
Revises: 758c43533848
Create Date: 2024-06-26 17:14:31.488150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82fb182288aa"
down_revision: Union[str, None] = "758c43533848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wikibase", sa.Column("country", sa.String(), nullable=True))
    op.add_column("wikibase", sa.Column("region", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase", "region")
    op.drop_column("wikibase", "country")
    # ### end Alembic commands ###
