"""triples

Revision ID: 83448d82b997
Revises: 8efce728b6f4
Create Date: 2024-07-08 14:05:01.777596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83448d82b997"
down_revision: Union[str, None] = "8efce728b6f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikibase_quantity_observation",
        sa.Column("total_triples", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase_quantity_observation", "total_triples")
    # ### end Alembic commands ###
