"""active_users

Revision ID: 9cbd76e2a3af
Revises: 24affa01347e
Create Date: 2025-09-03 18:26:01.647408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cbd76e2a3af"
down_revision: Union[str, None] = "24affa01347e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month") as batch_op:
        batch_op.add_column(
            sa.Column("user_count_five_plus", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("user_count_no_bot_five_plus", sa.Integer(), nullable=True)
        )
    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.add_column(
            sa.Column("user_count_five_plus", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("user_count_no_bot_five_plus", sa.Integer(), nullable=True)
        )
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.add_column(
            sa.Column("user_count_five_plus", sa.Integer(), nullable=True)
        )
    with op.batch_alter_table("wikibase_recent_changes_observation") as batch_op:
        batch_op.add_column(
            sa.Column("human_change_user_count_five_plus", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("bot_change_user_count_five_plus", sa.Integer(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_recent_changes_observation") as batch_op:
        batch_op.drop_column("bot_change_user_count_five_plus")
        batch_op.drop_column("human_change_user_count_five_plus")
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.drop_column("user_count_five_plus")
    with op.batch_alter_table("wikibase_log_observation_month_type") as batch_op:
        batch_op.drop_column("user_count_no_bot_five_plus")
        batch_op.drop_column("user_count_five_plus")
    with op.batch_alter_table("wikibase_log_observation_month") as batch_op:
        batch_op.drop_column("user_count_no_bot_five_plus")
        batch_op.drop_column("user_count_five_plus")
    # ### end Alembic commands ###
