"""Description

Revision ID: 9f69274a14d2
Revises: 517f5144d66e
Create Date: 2024-07-09 11:34:43.985193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f69274a14d2"
down_revision: Union[str, None] = "517f5144d66e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wikibase", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase", "description")
    # ### end Alembic commands ###
