"""Connectivity Counts II

Revision ID: a824ffd7b9a1
Revises: e441cf0ebffb
Create Date: 2024-06-20 15:23:00.764332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a824ffd7b9a1"
down_revision: Union[str, None] = "e441cf0ebffb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_connectivity_observation_object_relationship_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_connectivity_observation_id", sa.Integer(), nullable=False),
        sa.Column("relationship_count", sa.Integer(), nullable=False),
        sa.Column("object_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_connectivity_observation_id"],
            ["wikibase_connectivity_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_connectivity_observation_id",
            "relationship_count",
            name="unique_observation_relationship_count2",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_connectivity_observation_object_relationship_count")
    # ### end Alembic commands ###
