"""external identifiers and urls

Revision ID: bcc81afe3bc3
Revises: 215716d3ef0e
Create Date: 2025-07-01 16:26:53.381242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc81afe3bc3'
down_revision: Union[str, None] = '215716d3ef0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikibase_quantity_observation', sa.Column('total_external_identifier_properties', sa.Integer(), nullable=True))
    op.add_column('wikibase_quantity_observation', sa.Column('total_external_identifier_statements', sa.Integer(), nullable=True))
    op.add_column('wikibase_quantity_observation', sa.Column('total_url_properties', sa.Integer(), nullable=True))
    op.add_column('wikibase_quantity_observation', sa.Column('total_url_statements', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wikibase_quantity_observation', 'total_url_statements')
    op.drop_column('wikibase_quantity_observation', 'total_url_properties')
    op.drop_column('wikibase_quantity_observation', 'total_external_identifier_statements')
    op.drop_column('wikibase_quantity_observation', 'total_external_identifier_properties')
    # ### end Alembic commands ###
