"""Mandatory Mark Test

Revision ID: be21c6bee8af
Revises: 50eab022143d
Create Date: 2024-07-24 16:43:47.983446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be21c6bee8af'
down_revision: Union[str, None] = '50eab022143d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column( 'test',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column( 'test',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
