"""Mandatory Software Relationship

Revision ID: bf635fa3a7ce
Revises: 0833cb54870f
Create Date: 2024-10-16 23:57:48.573469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf635fa3a7ce"
down_revision: Union[str, None] = "0833cb54870f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.alter_column(
            "wikibase_software_id", existing_type=sa.INTEGER(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.alter_column(
            "wikibase_software_id", existing_type=sa.INTEGER(), nullable=True
        )
    # ### end Alembic commands ###
