"""Month Type

Revision ID: dc5539ca38f5
Revises: f3633b2b02c2
Create Date: 2024-07-16 14:53:17.111619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc5539ca38f5"
down_revision: Union[str, None] = "f3633b2b02c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_log_observation_month_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("log_month_observation_id", sa.Integer(), nullable=False),
        sa.Column(
            "log_type",
            sa.Enum(
                "ABUSE_FILTER_CREATE",
                "COMMENTS_CREATE",
                "COMMENTS_DELETE",
                "CONSUMER_APPROVE",
                "CONSUMER_CREATE",
                "CONSUMER_PROPOSE",
                "CONSUMER_REJECT",
                "IMAGE_OVERWRITE",
                "IMAGE_REVERT",
                "IMAGE_UPLOAD",
                "IMPORT",
                "INTERWIKI_CREATE",
                "INTERWIKI_DELETE",
                "INTERWIKI_EDIT",
                "ITEM_CREATE",
                "ITEM_DELETE",
                "MOVE",
                "PAGE_CREATE",
                "PAGE_DELETE",
                "PATROL",
                "PATROL_AUTO",
                "PROPERTY_CREATE",
                "PROPERTY_DELETE",
                "PROTECT",
                "TAG_CREATE",
                "UNDO_DELETE",
                "USER_BLOCK",
                "USER_UNBLOCK",
                "USER_CREATE",
                "USER_DELETE",
                "USER_MERGE",
                "USER_RENAME",
                "USER_RIGHTS",
                "WIKI_NAMESPACES",
                "WIKI_RIGHTS",
                "WIKI_SETTINGS",
                name="wikibaselogtype",
            ).with_variant(sa.String, "sqlite"),
            nullable=False,
        ),
        sa.Column("first_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("log_count", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("user_count_no_bot", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["log_month_observation_id"],
            ["wikibase_log_observation_month.id"],
            name="month_observation",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_log_observation_month_type")
    # ### end Alembic commands ###
