"""Month Type

Revision ID: dc5539ca38f5
Revises: f3633b2b02c2
Create Date: 2024-07-16 14:53:17.111619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc5539ca38f5"
down_revision: Union[str, None] = "f3633b2b02c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_log_observation_month_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("log_month_observation_id", sa.Integer(), nullable=False),
        sa.Column(
            "log_type",
            sa.Enum(
                "ABUSE_FILTER_CREATE",
                "ABUSE_FILTER_MODIFIY",
                "ACHIEVEMENT_BADGE",
                "APPROVE",
                "COMMENTS_CREATE",
                "COMMENTS_DELETE",
                "CONSUMER_APPROVE",
                "CONSUMER_CREATE",
                "CONSUMER_DISABLE",
                "CONSUMER_PROPOSE",
                "CONSUMER_REJECT",
                "CONSUMER_UPDATE",
                "CONFIG_UPDATE",
                "CONTENT_MODEL_CREATE",
                "CONTENT_MODEL_CHANGE",
                "DATADUMP_DELETE",
                "DATADUMP_GENERATE",
                "EVENT_DELETE",
                "EXPORT_PDF",
                "FEEDBACK_CREATE",
                "FEEDBACK_FEATURE",
                "FEEDBACK_FLAG",
                "FEEDBACK_FLAG_INAPPROPRIATE",
                "FEEDBACK_HIDE",
                "FEEDBACK_NO_ACTION",
                "FEEDBACK_RESOLVE",
                "IMPORT",
                "IMPORT_HTML",
                "INTERWIKI_CREATE",
                "INTERWIKI_DELETE",
                "INTERWIKI_EDIT",
                "ITEM_CREATE",
                "ITEM_DELETE",
                "LOCK_FLOW_LOCK_TOPIC",
                "MEDIA_APPROVE",
                "MEDIA_OVERWRITE",
                "MEDIA_REVERT",
                "MEDIA_UPLOAD",
                "MOVE",
                "PAGE_CREATE",
                "PAGE_DELETE",
                "PAGE_TRANSLATE",
                "PAGE_TRANSLATE_DELETE_FOK",
                "PAGE_TRANSLATE_DELETE_LOK",
                "PAGE_TRANSLATE_MARK",
                "PAGE_TRANSLATE_UNMARK",
                "PAGE_UPDATE_LANGUAGE",
                "PATROL",
                "PATROL_AUTO",
                "PROFILE",
                "PROPERTY_CREATE",
                "PROPERTY_DELETE",
                "PROTECT",
                "REDIRECT_DELETE",
                "REDIRECT_MOVE",
                "REVISION_DELETE",
                "TABLE_CREATE",
                "TABLE_DELETE",
                "TAG_CREATE",
                "THANK",
                "UNAPPROVE",
                "UNDO_DELETE",
                "UNPROTECT",
                "USER_BLOCK",
                "USER_UNBLOCK",
                "USER_CREATE",
                "USER_DELETE",
                "USER_MERGE",
                "USER_RENAME",
                "USER_RIGHTS",
                "WIKI_FARM",
                "WIKI_GROUP_DELETE",
                "WIKI_NAMESPACES",
                "WIKI_RIGHTS",
                "WIKI_SETTINGS",
                name="wikibaselogtype",
            ),
            nullable=False,
        ),
        sa.Column("first_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("log_count", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("user_count_no_bot", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["log_month_observation_id"],
            ["wikibase_log_observation_month.id"],
            name="month_observation",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_log_observation_month_type")
    # ### end Alembic commands ###
