"""WBS Bundled

Revision ID: e6685295bb5c
Revises: eeea3f16e54c
Create Date: 2025-03-13 12:47:56.480587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6685295bb5c"
down_revision: Union[str, None] = "eeea3f16e54c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software", recreate="always") as batch_op:
        batch_op.add_column(
            sa.Column("wbs_bundled", sa.Boolean(), nullable=True),
            insert_after="mw_bundled",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software") as batch_op:
        batch_op.drop_column("wbs_bundled")
    # ### end Alembic commands ###
