"""Optional Region

Revision ID: fd116456e347
Revises: 43064b39c3a0
Create Date: 2024-07-22 13:38:00.480580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd116456e347"
down_revision: Union[str, None] = "43064b39c3a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("region", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("region", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
