"""Unique Groups

Revision ID: 11f54d94f985
Revises: 7b6bec51442f
Create Date: 2024-06-17 11:55:51.232087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11f54d94f985"
down_revision: Union[str, None] = "7b6bec51442f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_user_group") as batch_op:
        batch_op.create_unique_constraint("unique_group_name", ["group_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_user_group") as batch_op:
        batch_op.drop_constraint("unique_group_name", type_="unique")
    # ### end Alembic commands ###
