"""WikibaseType

Revision ID: 215716d3ef0e
Revises: e6685295bb5c
Create Date: 2025-04-17 01:04:47.417648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "215716d3ef0e"
down_revision: Union[str, None] = "e6685295bb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.add_column(
            sa.Column(
                "wb_type",
                sa.Enum("SUITE", "CLOUD", "OTHER", name="wikibasetype").with_variant(
                    sa.CHAR(5), "sqlite"
                ),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.drop_column("wb_type")
    # ### end Alembic commands ###
