"""non-optional

Revision ID: 22198423bfca
Revises: 82fb182288aa
Create Date: 2024-06-26 17:16:20.128638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22198423bfca"
down_revision: Union[str, None] = "82fb182288aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("region", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("region", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
