"""rename ttfv II

Revision ID: 24affa01347e
Revises: 0ec4bac56660
Create Date: 2025-06-06 13:41:33.959371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24affa01347e"
down_revision: Union[str, None] = "0ec4bac56660"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_item_date") as batch_op:
        batch_op.drop_constraint("unique_observation_q", type_="unique")
        batch_op.drop_constraint("observation", type_="foreignkey")
        batch_op.alter_column(
            "wikibase_initial_value_observation_id",
            new_column_name="wikibase_time_to_first_value_observation_id",
        )
    with op.batch_alter_table("wikibase_item_date") as batch_op:
        batch_op.create_unique_constraint(
            "unique_observation_q", ["wikibase_time_to_first_value_observation_id", "q"]
        )
        batch_op.create_foreign_key(
            "observation",
            "wikibase_time_to_first_value_observation",
            ["wikibase_time_to_first_value_observation_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_item_date") as batch_op:
        batch_op.drop_constraint("unique_observation_q", type_="unique")
        batch_op.drop_constraint("observation", type_="foreignkey")
        batch_op.alter_column(
            "wikibase_time_to_first_value_observation_id",
            new_column_name="wikibase_initial_value_observation_id",
        )
    with op.batch_alter_table("wikibase_item_date") as batch_op:
        batch_op.create_foreign_key(
            "observation",
            "wikibase_time_to_first_value_observation",
            ["wikibase_initial_value_observation_id"],
            ["id"],
        )
        batch_op.create_unique_constraint(
            "unique_observation_q", ["wikibase_initial_value_observation_id", "q"]
        )
    # ### end Alembic commands ###
