"""Item / Relationship Counts

Revision ID: 3078a807f9fa
Revises: c82d21577d02
Create Date: 2024-06-18 12:08:50.824991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3078a807f9fa"
down_revision: Union[str, None] = "c82d21577d02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_quantity_observation_item_relationship_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_quantity_observation_id", sa.Integer(), nullable=False),
        sa.Column("relationship_count", sa.Integer(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_quantity_observation_id"],
            ["wikibase_quantity_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_quantity_observation_id",
            "relationship_count",
            name="unique_quantity_observation_item_relationship_count",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_quantity_observation_item_relationship_count")
    # ### end Alembic commands ###
