"""Fetched

Revision ID: 3b5538b2faec
Revises: 7fd538ca8735
Create Date: 2024-10-17 12:36:32.239393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b5538b2faec"
down_revision: Union[str, None] = "7fd538ca8735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikibase_software",
        sa.Column("fetched", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase_software", "fetched")
    # ### end Alembic commands ###
