"""User Type

Revision ID: 3c1f7719fedc
Revises: dc5539ca38f5
Create Date: 2024-07-16 15:53:21.652616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c1f7719fedc"
down_revision: Union[str, None] = "dc5539ca38f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_log_observation_month_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("log_month_observation_id", sa.Integer(), nullable=False),
        sa.Column(
            "log_type",
            sa.Enum("BOT", "MISSING", "USER", "NONE", name="wikibaseusertype"),
            nullable=False,
        ),
        sa.Column("first_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("log_count", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["log_month_observation_id"],
            ["wikibase_log_observation_month.id"],
            name="month_observation",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_log_observation_month_user")
    # ### end Alembic commands ###
