"""unoptional

Revision ID: 3e4e94ba1d61
Revises: 4a9dafdd7b93
Create Date: 2024-06-26 17:03:15.264666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e4e94ba1d61"
down_revision: Union[str, None] = "4a9dafdd7b93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column(
            "wikibase_name", existing_type=sa.VARCHAR(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column(
            "wikibase_name", existing_type=sa.VARCHAR(), nullable=True
        )
    # ### end Alembic commands ###
