"""Unique Constraints

Revision ID: 43064b39c3a0
Revises: c585ae1a8a67
Create Date: 2024-07-16 23:35:17.697990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43064b39c3a0"
down_revision: Union[str, None] = "c585ae1a8a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.create_unique_constraint(
            "unique_observation_user_type", ["log_month_observation_id", "user_type"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation_month_user") as batch_op:
        batch_op.drop_constraint("unique_observation_user_type", type_="unique")
    # ### end Alembic commands ###
