"""name

Revision ID: 4a9dafdd7b93
Revises: a168eb215de7
Create Date: 2024-06-26 16:55:17.142042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a9dafdd7b93"
down_revision: Union[str, None] = "a168eb215de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.add_column(sa.Column("wikibase_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("organization", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.drop_column("organization")
        batch_op.drop_column("wikibase_name")
    # ### end Alembic commands ###
