"""redundant

Revision ID: 758c43533848
Revises: 3e4e94ba1d61
Create Date: 2024-06-26 17:05:54.849080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "758c43533848"
down_revision: Union[str, None] = "3e4e94ba1d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.drop_column("action_query_url")
        batch_op.drop_column("sparql_query_url")
        batch_op.drop_column("special_version_url")
        batch_op.drop_column("sparql_endpoint_url")
        batch_op.drop_column("base_url")
        batch_op.drop_column("index_query_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.add_column(sa.Column("index_query_url", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("base_url", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column("sparql_endpoint_url", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("special_version_url", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(sa.Column("sparql_query_url", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("action_query_url", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
