"""Optional

Revision ID: 78b8f08650bc
Revises: ad7de7954d2f
Create Date: 2024-07-03 23:25:22.184178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78b8f08650bc"
down_revision: Union[str, None] = "ad7de7954d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.alter_column(
            "first_log_date", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            "last_log_date", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            "last_log_user_type",
            existing_type=sa.VARCHAR(length=4),
            type_=sa.Enum("BOT", "MISSING", "USER", "NONE", name="wikibaseusertype"),
            nullable=True,
        )
        batch_op.alter_column(
            "last_month_log_count", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "last_month_user_count", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "last_month_user_count_no_bot", existing_type=sa.INTEGER(), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.alter_column(
            "last_month_user_count_no_bot", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "last_month_user_count", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "last_month_log_count", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "last_log_user_type",
            existing_type=sa.Enum(
                "BOT", "MISSING", "USER", "NONE", name="wikibaseusertype"
            ),
            type_=sa.VARCHAR(length=4),
            nullable=False,
        )
        batch_op.alter_column(
            "last_log_date", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            "first_log_date", existing_type=sa.DATETIME(), nullable=False
        )
    # ### end Alembic commands ###
