"""ei

Revision ID: 825702b9d344
Revises: 9cbd76e2a3af
Create Date: 2025-09-10 12:52:38.774076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from model.database import (
    WikibaseExternalIdentifierObservationModel,
    WikibaseQuantityObservationModel,
)


# revision identifiers, used by Alembic.
revision: str = "825702b9d344"
down_revision: Union[str, None] = "9cbd76e2a3af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_external_identifier_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_external_identifier_properties", sa.Integer(), nullable=True),
        sa.Column("total_external_identifier_statements", sa.Integer(), nullable=True),
        sa.Column("total_url_properties", sa.Integer(), nullable=True),
        sa.Column("total_url_statements", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Preserve Existing Observations
    insert_query = sa.insert(WikibaseExternalIdentifierObservationModel).from_select(
        [
            WikibaseExternalIdentifierObservationModel.wikibase_id,
            WikibaseExternalIdentifierObservationModel.observation_date,
            WikibaseExternalIdentifierObservationModel.returned_data,
            WikibaseExternalIdentifierObservationModel.total_external_identifier_properties,
            WikibaseExternalIdentifierObservationModel.total_external_identifier_statements,
            WikibaseExternalIdentifierObservationModel.total_url_properties,
            WikibaseExternalIdentifierObservationModel.total_url_statements,
        ],
        sa.select(
            WikibaseQuantityObservationModel.wikibase_id,
            WikibaseQuantityObservationModel.observation_date,
            WikibaseQuantityObservationModel.returned_data,
            sa.text("total_external_identifier_properties"),
            sa.text("total_external_identifier_statements"),
            sa.text("total_url_properties"),
            sa.text("total_url_statements"),
        ).where(
            sa.or_(
                sa.text("total_external_identifier_properties IS NOT NULL"),
                sa.text("total_external_identifier_statements IS NOT NULL"),
                sa.text("total_url_properties IS NOT NULL"),
                sa.text("total_url_statements IS NOT NULL"),
            )
        ),
    )
    op.execute(insert_query)

    # Update Quantity to reflect lower expectations
    update_query = sa.update(WikibaseQuantityObservationModel).values(
        returned_data=sa.and_(
            WikibaseQuantityObservationModel.total_items != None,
            WikibaseQuantityObservationModel.total_lexemes != None,
            WikibaseQuantityObservationModel.total_properties != None,
            WikibaseQuantityObservationModel.total_triples != None,
        )
    )
    op.execute(update_query)

    with op.batch_alter_table("wikibase_quantity_observation") as batch_op:
        batch_op.drop_column("total_url_properties")
        batch_op.drop_column("total_external_identifier_properties")
        batch_op.drop_column("total_external_identifier_statements")
        batch_op.drop_column("total_url_statements")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_quantity_observation") as batch_op:
        batch_op.add_column(
            sa.Column("total_url_statements", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "total_external_identifier_statements", sa.INTEGER(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "total_external_identifier_properties", sa.INTEGER(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("total_url_properties", sa.INTEGER(), nullable=True)
        )
    op.drop_table("wikibase_external_identifier_observation")
    # ### end Alembic commands ###
