"""optional

Revision ID: 8c2df588e047
Revises: 4e46b70c3f46
Create Date: 2024-06-25 17:59:36.903048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c2df588e047"
down_revision: Union[str, None] = "4e46b70c3f46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.alter_column("version", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_version") as batch_op:
        batch_op.alter_column("version", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
