"""mandatory check

Revision ID: 8efce728b6f4
Revises: ec860c501b6a
Create Date: 2024-07-08 12:07:37.001127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8efce728b6f4"
down_revision: Union[str, None] = "ec860c501b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("valid", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase") as batch_op:
        batch_op.alter_column("valid", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
