"""urls

Revision ID: 93d8f0a13a14
Revises: 8c2df588e047
Create Date: 2024-06-26 15:47:45.773456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93d8f0a13a14"
down_revision: Union[str, None] = "8c2df588e047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_url",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column(
            "url_type",
            sa.Enum(
                "BASE_URL",
                "ACTION_QUERY_URL",
                "INDEX_QUERY_URL",
                "SPARQL_ENDPOINT_URL",
                "SPARQL_QUERY_URL",
                "SPECIAL_VERSION_URL",
                name="wikibaseurltype",
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wikibase_id", "url_type", name="unique_wikibase_url_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_url")
    # ### end Alembic commands ###
