"""Logs

Revision ID: ad7de7954d2f
Revises: 22198423bfca
Create Date: 2024-06-27 08:03:21.118882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad7de7954d2f"
down_revision: Union[str, None] = "22198423bfca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_log_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_log_user_type",
            sa.Enum("BOT", "MISSING", "USER", "NONE", name="wikibaseusertype"),
            nullable=False,
        ),
        sa.Column("last_month_log_count", sa.Integer(), nullable=False),
        sa.Column("last_month_user_count", sa.Integer(), nullable=False),
        sa.Column("last_month_user_count_no_bot", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_log_observation")
    # ### end Alembic commands ###
