"""Month

Revision ID: b7d2fb238541
Revises: 9f69274a14d2
Create Date: 2024-07-16 13:51:15.936237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7d2fb238541"
down_revision: Union[str, None] = "9f69274a14d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_log_observation_month",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_log_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_log_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("log_count", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("user_count_no_bot", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.add_column(sa.Column("first_month_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_month_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "first_month", "wikibase_log_observation_month", ["first_month_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "last_month", "wikibase_log_observation_month", ["last_month_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.drop_constraint("last_month", type_="foreignkey")
        batch_op.drop_constraint("first_month", type_="foreignkey")
        batch_op.drop_column("last_month_id")
        batch_op.drop_column("first_month_id")
    op.drop_table("wikibase_log_observation_month")
    # ### end Alembic commands ###
