"""Quantity II

Revision ID: c82d21577d02
Revises: da50722c428f
Create Date: 2024-06-18 02:31:33.433739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c82d21577d02"
down_revision: Union[str, None] = "da50722c428f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikibase_quantity_observation",
        sa.Column("total_items", sa.Integer(), nullable=True),
    )
    op.add_column(
        "wikibase_quantity_observation",
        sa.Column("total_properties", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase_quantity_observation", "total_properties")
    op.drop_column("wikibase_quantity_observation", "total_items")
    # ### end Alembic commands ###
