"""Archived

Revision ID: ced691eaf66e
Revises: 3b5538b2faec
Create Date: 2024-10-17 16:19:32.355862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ced691eaf66e"
down_revision: Union[str, None] = "3b5538b2faec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software") as batch_op:
        batch_op.add_column(sa.Column("archived", sa.Boolean(), nullable=True))
    with op.batch_alter_table("wikibase_software_tag") as batch_op:
        batch_op.create_unique_constraint("unique_tag", ["tag"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_software_tag") as batch_op:
        batch_op.drop_constraint("unique_tag", type_="unique")
    with op.batch_alter_table("wikibase_software") as batch_op:
        batch_op.drop_column("archived")
    # ### end Alembic commands ###
