"""special:version url

Revision ID: d411cfb9428e
Revises: e5011debee83
Create Date: 2024-06-25 01:53:08.368177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d411cfb9428e"
down_revision: Union[str, None] = "e5011debee83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikibase", sa.Column("special_version_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase", "special_version_url")
    # ### end Alembic commands ###
