"""files

Revision ID: e3ecd40e3851
Revises: 67cb5d75f92b
Create Date: 2024-08-20 21:47:54.370521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3ecd40e3851"
down_revision: Union[str, None] = "67cb5d75f92b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "wikibase_statistics_observation", recreate="always"
    ) as batch_op:
        batch_op.add_column(
            sa.Column("total_files", sa.Integer(), nullable=True),
            insert_after="content_pages",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_statistics_observation") as batch_op:
        batch_op.drop_column("total_files")
    # ### end Alembic commands ###
