"""Connectivity Counts

Revision ID: e441cf0ebffb
Revises: f4e79c308443
Create Date: 2024-06-20 14:42:49.128519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e441cf0ebffb"
down_revision: Union[str, None] = "f4e79c308443"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_connectivity_observation_item_relationship_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_connectivity_observation_id", sa.Integer(), nullable=False),
        sa.Column("relationship_count", sa.Integer(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_connectivity_observation_id"],
            ["wikibase_connectivity_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_connectivity_observation_id",
            "relationship_count",
            name="unique_connectivity_observation_item_relationship_count",
        ),
    )
    op.drop_table("wikibase_quantity_observation_item_relationship_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_quantity_observation_item_relationship_count",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("wikibase_quantity_observation_id", sa.INTEGER(), nullable=False),
        sa.Column("relationship_count", sa.INTEGER(), nullable=False),
        sa.Column("item_count", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_quantity_observation_id"],
            ["wikibase_quantity_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_quantity_observation_id",
            "relationship_count",
            name="unique_quantity_observation_item_relationship_count",
        ),
    )
    op.drop_table("wikibase_connectivity_observation_item_relationship_count")
    # ### end Alembic commands ###
