"""Property Usage

Revision ID: e5011debee83
Revises: a824ffd7b9a1
Create Date: 2024-06-24 14:58:07.373833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5011debee83"
down_revision: Union[str, None] = "a824ffd7b9a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikibase_property_usage_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wikibase_id", sa.Integer(), nullable=False),
        sa.Column("anything", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_id"], ["wikibase.id"], name="observation_wikibase"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wikibase_property_usage_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "wikibase_property_usage_observation_id", sa.Integer(), nullable=False
        ),
        sa.Column("property_url", sa.String(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wikibase_property_usage_observation_id"],
            ["wikibase_property_usage_observation.id"],
            name="observation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wikibase_property_usage_observation_id",
            "property_url",
            name="unique_observation_property_url",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikibase_property_usage_count")
    op.drop_table("wikibase_property_usage_observation")
    # ### end Alembic commands ###
