"""Valid

Revision ID: ec860c501b6a
Revises: 78b8f08650bc
Create Date: 2024-07-08 12:02:56.720042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec860c501b6a"
down_revision: Union[str, None] = "78b8f08650bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wikibase", sa.Column("valid", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikibase", "valid")
    # ### end Alembic commands ###
