"""Redundant

Revision ID: f3633b2b02c2
Revises: b7d2fb238541
Create Date: 2024-07-16 14:21:40.751068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3633b2b02c2"
down_revision: Union[str, None] = "b7d2fb238541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.drop_column("last_month_log_count")
        batch_op.drop_column("last_month_user_count")
        batch_op.drop_column("last_month_user_count_no_bot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wikibase_log_observation") as batch_op:
        batch_op.add_column(
            sa.Column("last_month_user_count_no_bot", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_month_user_count", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_month_log_count", sa.INTEGER(), nullable=True)
        )
    # ### end Alembic commands ###
