"""Resolvers"""

from resolvers.add_wikibase import add_wikibase
from resolvers.authentication import authenticate
from resolvers.get_aggregate_created import get_aggregate_created
from resolvers.get_aggregate_languages import get_language_list
from resolvers.get_aggregate_property_popularity import (
    get_aggregate_property_popularity,
)
from resolvers.get_aggregate_quantity import get_aggregate_quantity
from resolvers.get_aggregate_recent_changes import get_aggregate_recent_changes
from resolvers.get_aggregate_software_version import get_aggregate_version
from resolvers.get_aggregate_statistics import get_aggregate_statistics
from resolvers.get_aggregate_users import get_aggregate_users
from resolvers.get_software_list import get_software_list
from resolvers.get_wikibase import get_wikibase
from resolvers.get_wikibase_list import get_wikibase_list
