"""cloud_api_data"""

from fetch_data.cloud_api_data.get_cloud_api_data import fetch_cloud_instances
from fetch_data.cloud_api_data.update_cloud_instances import update_cloud_instances
from fetch_data.cloud_api_data.wikibase_cloud_instance import WikibaseCloudInstance
