"""Test Sort Wikibase List"""

import pytest
from tests.test_query.wikibase_list_query import WIKIBASE_LIST_QUERY
from tests.test_schema import test_schema
from tests.utils import assert_layered_property_value, assert_page_meta


@pytest.mark.asyncio
@pytest.mark.query
@pytest.mark.dependency(
    name="sort-edits-asc", depends=["mutate-cloud-instances"], scope="session"
)
async def test_wikibase_list_query_sort_edits_asc():
    """Test Sort Edits Ascending"""

    result = await test_schema.execute(
        WIKIBASE_LIST_QUERY,
        variable_values={
            "pageNumber": 1,
            "pageSize": 11,
            "sortBy": {"column": "EDITS", "dir": "ASC"},
        },
    )

    assert result.errors is None
    assert result.data is not None
    assert "wikibaseList" in result.data
    assert_page_meta(result.data["wikibaseList"], 1, 11, 11, 1)

    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            0,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            0,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            1,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            1,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            2,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            2,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            3,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            3,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            4,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            4,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            5,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            5,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            6,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            6,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            7,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            7,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            8,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            8,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            9,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            9,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            10,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            10,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )


@pytest.mark.asyncio
@pytest.mark.query
@pytest.mark.dependency(
    name="sort-edits-desc", depends=["mutate-cloud-instances"], scope="session"
)
async def test_wikibase_list_query_sort_edits_desc():
    """Test Sort Edits Descending"""

    result = await test_schema.execute(
        WIKIBASE_LIST_QUERY,
        variable_values={
            "pageNumber": 1,
            "pageSize": 11,
            "sortBy": {"column": "EDITS", "dir": "DESC"},
        },
    )

    assert result.errors is None
    assert result.data is not None
    assert "wikibaseList" in result.data
    assert_page_meta(result.data["wikibaseList"], 1, 11, 11, 1)

    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            0,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            0,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            1,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            1,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            2,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            2,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            3,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            3,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            4,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            4,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            5,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            5,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            6,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            6,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            7,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            7,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            8,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            8,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            9,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            9,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            10,
            "recentChangesObservations",
            "mostRecent",
            "botChangeCount",
        ],
        0,
    )
    assert_layered_property_value(
        result.data,
        [
            "wikibaseList",
            "data",
            10,
            "recentChangesObservations",
            "mostRecent",
            "humanChangeCount",
        ],
        0,
    )
