URL_FILENAME = "test-url.xlsx"
USER_DATA_FILENAME = "test-user-data.xlsx"

COMPLETED_FILENAME = "test-full.xlsx"

URL_MASTER_LIST = [
    "https://portal.mardi4nfdi.de",
    "https://linkedopendata.eu",
    "https://lingualibre.org",
    "https://lod.enslaved.org",
    "https://database.factgrid.de",
    "https://data.biblissima.fr",
    "https://zetawiki.com",
    "https://wikilex.seb35.fr",
    "https://femiwiki.com",
    "https://eltedata.elte-dh.hu",
    "https://api.kunstmuseum.nl",
    "https://artbase.rhizome.org",
    "https://base.semlab.io",
    "https://en.seminaverbi.bibleget.io",
    "https://ucronias.miraheze.org",
    "https://media.scoutwiki.org",
    "https://wiki.personaldata.io",
    "https://ixwiki.com",
    "https://data.uncyclomedia.org",
    "https://safernicotine.wiki/mediawiki",
    "https://www.openriskmanual.org/data",
    "https://data.wikitrek.org",
    "https://wiki.eagle-network.eu",
    "https://crystalpool.cxuesong.com",
    "https://bsd.neuroinf.jp",
    "https://adochs.arch.be",
    "https://data.mimotext.uni-trier.de",
    "https://encyclopediaofastrobiology.org",
    "https://akf.kgi.uni-mannheim.de",
    "https://wikibase.the-qa-company.com",
    "https://matvoc.nims.go.jp",
    "https://set.kuleuven.be",
    "https://wiki.bgbm.org",
    "https://wedapedia.pl",
    "https://www.wikonsult.org",
    "https://wikibase.semantic-kompakkt.de",
    "https://data.nonbinary.wiki",
    "https://librarybase.org/wiki",
    "https://base.transformap.co",
    "https://data.droidwiki.org",
    "https://wiki.toenniges.net",
    "https://base.imedwiki.org",
    "https://modelling.dissco.tech",
]
