name: Docs Lint

on:
  pull_request:
    paths:
      - "data/gx/**/*.json"
      - "*.md"
      - "**/*.md"
      - "*.yml"
      - "**/*.yml"
      - ".github/workflows/docs.yml"
      - "*.ini"
      - "**/*.ini"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: npm install
        run: npm install prettier prettier-plugin-ini

      - name: npm check
        run: |
          npx prettier --check --use-tabs data/gx/**/*.json
          npx prettier --check --use-tabs *.md **/*.md
          npx prettier --check --use-tabs *.yml **/*.yml
          npx prettier --check --plugin=prettier-plugin-ini --ini-space-around-equals true --tab-width 4 *.ini **/*.ini
