name: Docs Lint

on:
  pull_request:
    paths:
      - '**.md'
      - '**/*.md'

jobs:
  lint-check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: npm install
        run: npm install prettier

      - name: npm check
        run: |
          npx prettier --check --use-tabs *.md
          npx prettier --check --use-tabs docs/*.md
